/*
 * This source file was generated by the Gradle 'init' task
 */
package com.example.gradleproject2;

public class App {
    
    

    public static void main(String[] args) {
       // System.out.println(new App().getGreeting());
        Animal a = new Animal("cat",12,"female",4.5f);
        Humans h = new Humans("raj",12,"male",5.83f);
        Birds b  =new Birds("koyal",3,"female",true);
        Dog d = new Dog("dogesh",7,"male",7.3f,"bhau-bhau");
        
        System.out.println(a);
         System.out.println(h);
          System.out.println(b);
           System.out.println(d);
        
    }
}
